import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import img from "@/public/images/dashboard.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-center h-fit items-center bg-gray-200 px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"
    style={{
      backgroundImage: `url(${img.src})`,
backgroundPosition: "center",
backgroundRepeat: "no-repeat",
backgroundSize: "cover",
    }}
    >
      <div className=" shadow-lg p-8 h-fit w-full text-white rounded-lg flex flex-col justify-center text-center items-center z-10"
      style={{
          backgroundColor: "rgb(0 0 0 / 71%)",
      }}
      >
        {children}
      </div>
    </div>
      </body>
    </html>
  );
}
